#!/usr/bin/env bash
set -ex

if [ "$1" == "postcustomization" ]
then
	TMPDIR=${TMPDIR:-'/tmp'}
	echo "Running postcustomization at $(date)" >> ${TMPDIR}/postcust_output.txt
	echo -e "use-autogenerated\nuse-autogenerated" | passwd root
	chage -I -1 -m 0 -M -1 -E -1 root

	### Comment below line if you want to enable root password access
	### root password access is dangerous; ssh-key access is recommended
	sed -i '/^PermitRootLogin yes/d' /etc/ssh/sshd_config
	systemctl reload sshd.service

	\rm -f /.guest-customization-post-reboot-pending || true

	sync
	sync
fi

exit 0
