#!/usr/bin/env bash

set -e

# disable ipv6 to avoid possible connection errors
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.lo.disable_ipv6 = 1' >> /etc/sysctl.conf
sudo sysctl -p

# setup resolvconf for ubuntu 20
sudo echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
apt update
apt install resolvconf
systemctl restart resolvconf.service
while [ `systemctl is-active resolvconf` != 'active' ]; do echo 'waiting for resolvconf'; sleep 5; done
echo 'nameserver 8.8.8.8' >> /etc/resolvconf/resolv.conf.d/head
resolvconf -u

#systemctl restart networking.service
systemctl restart systemd-networkd.service
while [ `systemctl is-active systemd-networkd` != 'active' ]; do echo 'waiting for network'; sleep 5; done

growpart /dev/sda 1 || :
resize2fs /dev/sda1 || :

# redundancy: https://github.com/vmware/container-service-extension/issues/432
systemctl restart systemd-networkd.service
while [ `systemctl is-active systemd-networkd` != 'active' ]; do echo 'waiting for network'; sleep 5; done

echo 'installing kubernetes'

docker_ce_version=5:20.10.12~3-0~ubuntu-focal
containerd_version=1.4.12-1
kubernetes_tools_version=1.23.3-00
kubernetes_cni_version=0.8.7-00
weave_version=2.8.1
versioned_weave_file="/root/weave_v$(echo $weave_version | sed -r 's/\./\-/g').yml"
export DEBIAN_FRONTEND=noninteractive

apt-get -q update -o Acquire::Retries=3 -o Acquire::http::No-Cache=True -o Acquire::http::Timeout=30 -o Acquire::https::No-Cache=True -o Acquire::https::Timeout=30 -o Acquire::ftp::Timeout=30
apt-get -q install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get -q update -o Acquire::Retries=3 -o Acquire::http::No-Cache=True -o Acquire::http::Timeout=30 -o Acquire::https::No-Cache=True -o Acquire::https::Timeout=30 -o Acquire::ftp::Timeout=30
apt-get -q install -y docker-ce=$docker_ce_version docker-ce-cli=$docker_ce_version containerd.io=$containerd_version
apt-get -q install -y kubelet=$kubernetes_tools_version kubeadm=$kubernetes_tools_version kubectl=$kubernetes_tools_version kubernetes-cni=$kubernetes_cni_version

systemctl enable docker
systemctl daemon-reload
systemctl restart docker
while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done

# use containerd as CRI runtime
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
cat <<EOF | tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

modprobe overlay
modprobe br_netfilter

# Setup required sysctl params, these persist across reboots.
cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# Apply sysctl params without reboot
sysctl --system
mkdir -p /etc/containerd
containerd config default | tee /etc/containerd/config.toml

# Use systemd cgroup driver
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
sed '/containerd.runtimes.runc.options/a \            SystemdCgroup = true' /etc/containerd/config.toml > /etc/containerd/config.toml
systemctl restart containerd
while [ `systemctl is-active containerd` != 'active' ]; do echo 'waiting for containerd'; sleep 5; done

echo 'installing required software for NFS'
apt-get -q install -y nfs-common nfs-kernel-server
systemctl stop nfs-kernel-server.service
systemctl disable nfs-kernel-server.service

# prevent updates to software that CSE depends on
apt-mark hold open-vm-tools
apt-mark hold docker
apt-mark hold docker-ce
apt-mark hold docker-ce-cli
apt-mark hold containerd.io
apt-mark hold kubelet
apt-mark hold kubeadm
apt-mark hold kubectl
apt-mark hold kubernetes-cni
apt-mark hold nfs-common
apt-mark hold nfs-kernel-server
apt-mark hold shim-signed

echo 'upgrading the system'
apt-get -q update -o Acquire::Retries=3 -o Acquire::http::No-Cache=True -o Acquire::http::Timeout=30 -o Acquire::https::No-Cache=True -o Acquire::https::Timeout=30 -o Acquire::ftp::Timeout=30
apt-get -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

# Download weave.yml to /root/weave_v2-8-1.yml
touch $versioned_weave_file
export weave_yaml_content_b64="YXBpVmVyc2lvbjogdjEKa2luZDogTGlzdAppdGVtczoKICAtIGFwaVZlcnNpb246IHYxCiAgICBraW5kOiBTZXJ2aWNlQWNjb3VudAogICAgbWV0YWRhdGE6CiAgICAgIG5hbWU6IHdlYXZlLW5ldAogICAgICBsYWJlbHM6CiAgICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KICAtIGFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8vdjEKICAgIGtpbmQ6IENsdXN0ZXJSb2xlCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIGxhYmVsczoKICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgIHJ1bGVzOgogICAgICAtIGFwaUdyb3VwczoKICAgICAgICAgIC0gJycKICAgICAgICByZXNvdXJjZXM6CiAgICAgICAgICAtIHBvZHMKICAgICAgICAgIC0gbmFtZXNwYWNlcwogICAgICAgICAgLSBub2RlcwogICAgICAgIHZlcmJzOgogICAgICAgICAgLSBnZXQKICAgICAgICAgIC0gbGlzdAogICAgICAgICAgLSB3YXRjaAogICAgICAtIGFwaUdyb3VwczoKICAgICAgICAgIC0gZXh0ZW5zaW9ucwogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIC0gbmV0d29ya3BvbGljaWVzCiAgICAgICAgdmVyYnM6CiAgICAgICAgICAtIGdldAogICAgICAgICAgLSBsaXN0CiAgICAgICAgICAtIHdhdGNoCiAgICAgIC0gYXBpR3JvdXBzOgogICAgICAgICAgLSAnbmV0d29ya2luZy5rOHMuaW8nCiAgICAgICAgcmVzb3VyY2VzOgogICAgICAgICAgLSBuZXR3b3JrcG9saWNpZXMKICAgICAgICB2ZXJiczoKICAgICAgICAgIC0gZ2V0CiAgICAgICAgICAtIGxpc3QKICAgICAgICAgIC0gd2F0Y2gKICAgICAgLSBhcGlHcm91cHM6CiAgICAgICAgLSAnJwogICAgICAgIHJlc291cmNlczoKICAgICAgICAtIG5vZGVzL3N0YXR1cwogICAgICAgIHZlcmJzOgogICAgICAgIC0gcGF0Y2gKICAgICAgICAtIHVwZGF0ZQogIC0gYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQogICAga2luZDogQ2x1c3RlclJvbGVCaW5kaW5nCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIGxhYmVsczoKICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgIHJvbGVSZWY6CiAgICAgIGtpbmQ6IENsdXN0ZXJSb2xlCiAgICAgIG5hbWU6IHdlYXZlLW5ldAogICAgICBhcGlHcm91cDogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pbwogICAgc3ViamVjdHM6CiAgICAgIC0ga2luZDogU2VydmljZUFjY291bnQKICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgICAgICBuYW1lc3BhY2U6IGt1YmUtc3lzdGVtCiAgLSBhcGlWZXJzaW9uOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvL3YxCiAgICBraW5kOiBSb2xlCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KICAgICAgbGFiZWxzOgogICAgICAgIG5hbWU6IHdlYXZlLW5ldAogICAgcnVsZXM6CiAgICAgIC0gYXBpR3JvdXBzOgogICAgICAgICAgLSAnJwogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIC0gY29uZmlnbWFwcwogICAgICAgIHJlc291cmNlTmFtZXM6CiAgICAgICAgICAtIHdlYXZlLW5ldAogICAgICAgIHZlcmJzOgogICAgICAgICAgLSBnZXQKICAgICAgICAgIC0gdXBkYXRlCiAgICAgIC0gYXBpR3JvdXBzOgogICAgICAgICAgLSAnJwogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIC0gY29uZmlnbWFwcwogICAgICAgIHZlcmJzOgogICAgICAgICAgLSBjcmVhdGUKICAtIGFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8vdjEKICAgIGtpbmQ6IFJvbGVCaW5kaW5nCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KICAgICAgbGFiZWxzOgogICAgICAgIG5hbWU6IHdlYXZlLW5ldAogICAgcm9sZVJlZjoKICAgICAga2luZDogUm9sZQogICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgICAgYXBpR3JvdXA6IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8KICAgIHN1YmplY3RzOgogICAgICAtIGtpbmQ6IFNlcnZpY2VBY2NvdW50CiAgICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgICAgbmFtZXNwYWNlOiBrdWJlLXN5c3RlbQogIC0gYXBpVmVyc2lvbjogYXBwcy92MQogICAga2luZDogRGFlbW9uU2V0CiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogd2VhdmUtbmV0CiAgICAgIGxhYmVsczoKICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgICAgbmFtZXNwYWNlOiBrdWJlLXN5c3RlbQogICAgc3BlYzoKICAgICAgIyBXYWl0IDUgc2Vjb25kcyB0byBsZXQgcG9kIGNvbm5lY3QgYmVmb3JlIHJvbGxpbmcgbmV4dCBwb2QKICAgICAgc2VsZWN0b3I6CiAgICAgICAgbWF0Y2hMYWJlbHM6CiAgICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgICAgbWluUmVhZHlTZWNvbmRzOiA1CiAgICAgIHRlbXBsYXRlOgogICAgICAgIG1ldGFkYXRhOgogICAgICAgICAgbGFiZWxzOgogICAgICAgICAgICBuYW1lOiB3ZWF2ZS1uZXQKICAgICAgICBzcGVjOgogICAgICAgICAgaW5pdENvbnRhaW5lcnM6CiAgICAgICAgICAgIC0gbmFtZTogd2VhdmUtaW5pdAogICAgICAgICAgICAgIGltYWdlOiAnZ2hjci5pby93ZWF2ZXdvcmtzL2xhdW5jaGVyL3dlYXZlLWt1YmU6Mi44LjEnCiAgICAgICAgICAgICAgaW1hZ2VQdWxsUG9saWN5OiBBbHdheXMKICAgICAgICAgICAgICBjb21tYW5kOgogICAgICAgICAgICAgICAgLSAvaG9tZS93ZWF2ZS9pbml0LnNoCiAgICAgICAgICAgICAgZW52OgogICAgICAgICAgICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgICAgICAgICAgIHByaXZpbGVnZWQ6IHRydWUKICAgICAgICAgICAgICB2b2x1bWVNb3VudHM6CiAgICAgICAgICAgICAgICAtIG5hbWU6IGNuaS1iaW4KICAgICAgICAgICAgICAgICAgbW91bnRQYXRoOiAvaG9zdC9vcHQKICAgICAgICAgICAgICAgIC0gbmFtZTogY25pLWJpbjIKICAgICAgICAgICAgICAgICAgbW91bnRQYXRoOiAvaG9zdC9ob21lCiAgICAgICAgICAgICAgICAtIG5hbWU6IGNuaS1jb25mCiAgICAgICAgICAgICAgICAgIG1vdW50UGF0aDogL2hvc3QvZXRjCiAgICAgICAgICAgICAgICAtIG5hbWU6IGxpYi1tb2R1bGVzCiAgICAgICAgICAgICAgICAgIG1vdW50UGF0aDogL2xpYi9tb2R1bGVzCiAgICAgICAgICAgICAgICAtIG5hbWU6IHh0YWJsZXMtbG9jawogICAgICAgICAgICAgICAgICBtb3VudFBhdGg6IC9ydW4veHRhYmxlcy5sb2NrCiAgICAgICAgICAgICAgICAgIHJlYWRPbmx5OiBmYWxzZQogICAgICAgICAgY29udGFpbmVyczoKICAgICAgICAgICAgLSBuYW1lOiB3ZWF2ZQogICAgICAgICAgICAgIGNvbW1hbmQ6CiAgICAgICAgICAgICAgICAtIC9ob21lL3dlYXZlL2xhdW5jaC5zaAogICAgICAgICAgICAgIGVudjoKICAgICAgICAgICAgICAgIC0gbmFtZTogSU5JVF9DT05UQUlORVIKICAgICAgICAgICAgICAgICAgdmFsdWU6ICJ0cnVlIgogICAgICAgICAgICAgICAgLSBuYW1lOiBIT1NUTkFNRQogICAgICAgICAgICAgICAgICB2YWx1ZUZyb206CiAgICAgICAgICAgICAgICAgICAgZmllbGRSZWY6CiAgICAgICAgICAgICAgICAgICAgICBhcGlWZXJzaW9uOiB2MQogICAgICAgICAgICAgICAgICAgICAgZmllbGRQYXRoOiBzcGVjLm5vZGVOYW1lCiAgICAgICAgICAgICAgaW1hZ2U6ICdnaGNyLmlvL3dlYXZld29ya3MvbGF1bmNoZXIvd2VhdmUta3ViZToyLjguMScKICAgICAgICAgICAgICBpbWFnZVB1bGxQb2xpY3k6IEFsd2F5cwogICAgICAgICAgICAgIHJlYWRpbmVzc1Byb2JlOgogICAgICAgICAgICAgICAgaHR0cEdldDoKICAgICAgICAgICAgICAgICAgaG9zdDogMTI3LjAuMC4xCiAgICAgICAgICAgICAgICAgIHBhdGg6IC9zdGF0dXMKICAgICAgICAgICAgICAgICAgcG9ydDogNjc4NAogICAgICAgICAgICAgIHJlc291cmNlczoKICAgICAgICAgICAgICAgIHJlcXVlc3RzOgogICAgICAgICAgICAgICAgICBjcHU6IDUwbQogICAgICAgICAgICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgICAgICAgICAgIHByaXZpbGVnZWQ6IHRydWUKICAgICAgICAgICAgICB2b2x1bWVNb3VudHM6CiAgICAgICAgICAgICAgICAtIG5hbWU6IHdlYXZlZGIKICAgICAgICAgICAgICAgICAgbW91bnRQYXRoOiAvd2VhdmVkYgogICAgICAgICAgICAgICAgLSBuYW1lOiBkYnVzCiAgICAgICAgICAgICAgICAgIG1vdW50UGF0aDogL2hvc3QvdmFyL2xpYi9kYnVzCiAgICAgICAgICAgICAgICAgIHJlYWRPbmx5OiB0cnVlCiAgICAgICAgICAgICAgICAtIG1vdW50UGF0aDogL2hvc3QvZXRjL21hY2hpbmUtaWQKICAgICAgICAgICAgICAgICAgbmFtZTogY25pLW1hY2hpbmUtaWQKICAgICAgICAgICAgICAgICAgcmVhZE9ubHk6IHRydWUKICAgICAgICAgICAgICAgIC0gbmFtZTogeHRhYmxlcy1sb2NrCiAgICAgICAgICAgICAgICAgIG1vdW50UGF0aDogL3J1bi94dGFibGVzLmxvY2sKICAgICAgICAgICAgICAgICAgcmVhZE9ubHk6IGZhbHNlCiAgICAgICAgICAgIC0gbmFtZTogd2VhdmUtbnBjCiAgICAgICAgICAgICAgZW52OgogICAgICAgICAgICAgICAgLSBuYW1lOiBIT1NUTkFNRQogICAgICAgICAgICAgICAgICB2YWx1ZUZyb206CiAgICAgICAgICAgICAgICAgICAgZmllbGRSZWY6CiAgICAgICAgICAgICAgICAgICAgICBhcGlWZXJzaW9uOiB2MQogICAgICAgICAgICAgICAgICAgICAgZmllbGRQYXRoOiBzcGVjLm5vZGVOYW1lCiAgICAgICAgICAgICAgaW1hZ2U6ICdnaGNyLmlvL3dlYXZld29ya3MvbGF1bmNoZXIvd2VhdmUtbnBjOjIuOC4xJwogICAgICAgICAgICAgIGltYWdlUHVsbFBvbGljeTogQWx3YXlzCiNucGMtYXJncwogICAgICAgICAgICAgIHJlc291cmNlczoKICAgICAgICAgICAgICAgIHJlcXVlc3RzOgogICAgICAgICAgICAgICAgICBjcHU6IDUwbQogICAgICAgICAgICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgICAgICAgICAgIHByaXZpbGVnZWQ6IHRydWUKICAgICAgICAgICAgICB2b2x1bWVNb3VudHM6CiAgICAgICAgICAgICAgICAtIG5hbWU6IHh0YWJsZXMtbG9jawogICAgICAgICAgICAgICAgICBtb3VudFBhdGg6IC9ydW4veHRhYmxlcy5sb2NrCiAgICAgICAgICAgICAgICAgIHJlYWRPbmx5OiBmYWxzZQogICAgICAgICAgaG9zdE5ldHdvcms6IHRydWUKICAgICAgICAgIGRuc1BvbGljeTogQ2x1c3RlckZpcnN0V2l0aEhvc3ROZXQKICAgICAgICAgIGhvc3RQSUQ6IGZhbHNlCiAgICAgICAgICByZXN0YXJ0UG9saWN5OiBBbHdheXMKICAgICAgICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgICAgICAgc2VMaW51eE9wdGlvbnM6IHt9CiAgICAgICAgICBzZXJ2aWNlQWNjb3VudE5hbWU6IHdlYXZlLW5ldAogICAgICAgICAgdG9sZXJhdGlvbnM6CiAgICAgICAgICAgIC0gZWZmZWN0OiBOb1NjaGVkdWxlCiAgICAgICAgICAgICAgb3BlcmF0b3I6IEV4aXN0cwogICAgICAgICAgICAtIGVmZmVjdDogTm9FeGVjdXRlCiAgICAgICAgICAgICAgb3BlcmF0b3I6IEV4aXN0cwogICAgICAgICAgdm9sdW1lczoKICAgICAgICAgICAgLSBuYW1lOiB3ZWF2ZWRiCiAgICAgICAgICAgICAgaG9zdFBhdGg6CiAgICAgICAgICAgICAgICBwYXRoOiAvdmFyL2xpYi93ZWF2ZQogICAgICAgICAgICAtIG5hbWU6IGNuaS1iaW4KICAgICAgICAgICAgICBob3N0UGF0aDoKICAgICAgICAgICAgICAgIHBhdGg6IC9vcHQKICAgICAgICAgICAgLSBuYW1lOiBjbmktYmluMgogICAgICAgICAgICAgIGhvc3RQYXRoOgogICAgICAgICAgICAgICAgcGF0aDogL2hvbWUKICAgICAgICAgICAgLSBuYW1lOiBjbmktY29uZgogICAgICAgICAgICAgIGhvc3RQYXRoOgogICAgICAgICAgICAgICAgcGF0aDogL2V0YwogICAgICAgICAgICAtIG5hbWU6IGNuaS1tYWNoaW5lLWlkCiAgICAgICAgICAgICAgaG9zdFBhdGg6CiAgICAgICAgICAgICAgICBwYXRoOiAvZXRjL21hY2hpbmUtaWQKICAgICAgICAgICAgLSBuYW1lOiBkYnVzCiAgICAgICAgICAgICAgaG9zdFBhdGg6CiAgICAgICAgICAgICAgICBwYXRoOiAvdmFyL2xpYi9kYnVzCiAgICAgICAgICAgIC0gbmFtZTogbGliLW1vZHVsZXMKICAgICAgICAgICAgICBob3N0UGF0aDoKICAgICAgICAgICAgICAgIHBhdGg6IC9saWIvbW9kdWxlcwogICAgICAgICAgICAtIG5hbWU6IHh0YWJsZXMtbG9jawogICAgICAgICAgICAgIGhvc3RQYXRoOgogICAgICAgICAgICAgICAgcGF0aDogL3J1bi94dGFibGVzLmxvY2sKICAgICAgICAgICAgICAgIHR5cGU6IEZpbGVPckNyZWF0ZQogICAgICAgICAgcHJpb3JpdHlDbGFzc05hbWU6IHN5c3RlbS1ub2RlLWNyaXRpY2FsCiAgICAgIHVwZGF0ZVN0cmF0ZWd5OgogICAgICAgIHR5cGU6IFJvbGxpbmdVcGRhdGUKCg=="
echo $weave_yaml_content_b64 | base64 -d > $versioned_weave_file

# /etc/machine-id must be empty so that new machine-id gets assigned on boot (in our case boot is vApp deployment)
# https://jaylacroix.com/fixing-ubuntu-18-04-virtual-machines-that-fight-over-the-same-ip-address/
truncate -s 0 /etc/machine-id
rm /var/lib/dbus/machine-id || :
ln -fs /etc/machine-id /var/lib/dbus/machine-id || : # dbus/machine-id is symlink pointing to /etc/machine-id

sync
sync
echo 'customization completed'
